### ISSUE TITLE
URLs not consistent 

### ISSUE THREAD

**Issue by S6savahd** [ceurws/ToolsEswc#18]
why for some volumes the representing url for paper contains the term 'paper' and some now:
for example: http://ceur-ws.org/Vol-1011/#4 only shows the number and http://ceur-ws.org/Vol-744/#paper3 has the term paper, 
can't we be more persistent. 
this should be the same for all other like event, person, etc.

**Comment by liyakun** [comment]
@S6savahd this is because paper url in  _Vol-1011_ is like _http://ceur-ws.org/Vol-1011/1.pdf_, the processing tool will just take the _1_ as paper name, this also applies to others,  like _http://ceur-ws.org/Vol-1/vossen-long.pdf_, which will be _http://ceur-ws.org/Vol-1/#vossen-long_, we are not using term 'paper' as common name for papers.

For person, the uri is always like _http://ceur-ws.org/Vol-1011/#person_name_, and for event, the uri is always like _http://ceur-ws.org/Vol-1011/#event_, as we defined.

**Comment by S6savahd** [comment]
if this is what is extracted and we can not have any better way, please close the issue
